### ISSUE TITLE
Question: Version from Apple App Store trustable?

### ISSUE THREAD

**Issue by marcusmuench2342** [tilfinltd/aws-extend-switch-roles#259]
I was not sure where to place the question: There is a version of this extension in the Apple macOS App Store behind this link: https://apps.apple.com/de/app/aws-extend-switch-roles/id1592710340

It is provided by SourceCube Ltd. Is it an official release and can it be trusted, or might this be a modified version with some malicious "enhancement" in it, which happened to other OpenSource Apps which is why I am asking.

**Comment by tilfin** [comment]
I have allowed SourceCube Ltd to release a safari version. However, I do not guarantee its operation.
It does not always provide the same features as my releases. The feature related to supporters isn't implemented because it conflicts with 'in app purchase' of the AppStore.

The source is placed on https://github.com/SourceCube-Ltd/aws-extend-switch-roles/tree/safari-extension.

**Comment by marcusmuench2342** [comment]
Thank you for your reply!

**Comment by parkeyparker** [comment]
It would seem I'm a bit behind on the releases (It seems my GitHub notification settings were set wrong, now corrected). I'll take a look through the recent changes soon to see what can be incorporated without upsetting App Store review. I use the plugin daily so that helps with detecting any issues but I haven't yet setup a macOS Beta machine to test macOS Ventura.
