### ISSUE TITLE
Message "Failed to fetch user info from the AWS Management Console page" in first click

### ISSUE THREAD

**Issue by hramos8** [tilfinltd/aws-extend-switch-roles#318]
**Describe the bug**
Every first time I click on the plugin after entering the AWS console page, I receive the message "Failed to fetch user info from the AWS Management Console page." The same thing happens when I go to the page of another service within the same account (e.g., EC2). On the first click, the error message appears, and on the second click, the list is loaded correctly. I noticed this bug after the last update.

**To Reproduce**
1. Log on AWS console
2. Click on the plugin button (the error message appears)
3. Click again on the plugin button (the list is loaded correctly)
4. Go to the EC2 service
5. Click on the plugin button (the error message appears)
6. Click again on the plugin button (the list is loaded correctly)

**Expected behavior**
The list appear in first click

**Environment**
 - OS: Windows 11
 - Browser firefox 118.0.2 (64-bits)
 - Plugin version: 4.0.0

**Comment by tilfin** [comment]
At the time of the first click on the plugin icon, the AWS Management Console page load has not finished, so the account information cannot be taken and an error occurs. If you wait a bit and then perform the first click, you will not get an error. The initial loading of the plugin popup process may have speeded up since version 4, making that event more likely to occur.

I will try to find a way to make it less likely to happen.

**Comment by tilfin** [comment]
@hramos8 I found the cause of this problem.  https://discourse.mozilla.org/t/are-content-scripts-not-automatically-injected-anymore-with-manifest-v3/108146

1. Open `about:addons` (Manage Your Extensions)
2. Select **AWS Extend Switch Roles**
3. Select **Permissions**
4. Turn on the URLs you use in **Optional permissions for added functionality**.
